name: TelegramAuth
version: '${project.version}'
main: ru.humoridze.telegramAuth.TelegramAuth
api-version: '1.20'
author: humoridze

commands:
  login:
    description: 'Вход'
    aliases:
      - 'l'
  changepassword:
    description: 'Смена пароля'
    aliases:
      - 'cp'
  whitelist:
    description: 'Управление вайтлистом'
    usage: '/whitelist <add/remove/list> [игрок]'
    permission: 'telegramAuth.whitelist'

permissions:
  telegramAuth.whitelist:
    description: Управление вайтлистом плагина
    default: op
